#!/bin/sh
#
# exim      This shell script takes care of starting and stopping
#               exim.
#
# description: Mail Transfer Agent
#
### BEGIN INIT INFO
# Provides:          exim
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: exim
# Description:       exim smtp daemon
### END INIT INFO


BINARY=/usr/sbin/exim
PID=/var/run/exim.pid
EXIM_OPTS=
DAEMON="yes"
QUEUE="15m"
[ "$DAEMON" = yes ] && EXIM_OPTS="$EXIM_OPTS -bd"
[ -n "$QUEUE" ] && EXIM_OPTS="$EXIM_OPTS -q$QUEUE"

KILLALL=/usr/bin/killall
SPAM_PID=/var/run/spamd.pid

# See how we were called.
case "$1" in
  start)
        # Start daemons.
        echo -n "Starting exim: "
	$BINARY $EXIM_OPTS -oP $PID
        echo
	if [ -e /usr/bin/spamd ]; then /usr/bin/spamd -d -c -m 15 --ipv4 --pidfile=$SPAM_PID 1>/dev/null 2>/dev/null; fi
        ;;
  stop)
        # Stop daemons.
        echo -n "Shutting down exim: "
        if [ -e $PID ]; then kill `cat $PID`; fi
        echo

	if [ -e /usr/bin/spamd ]; then
		if [ -s $SPAM_PID ]; then
			kill `cat ${SPAM_PID}`
		else
			$KILLALL -r -9 spamd;
		fi
	fi
        ;;
  restart)
        $0 stop
        sleep 3
        $0 start
        ;;
  reload)
        if [ -e $PID ]; then kill -HUP `cat $PID`; fi
        ;;
  condrestart)
	$0 restart
        ;;
  status)
        status exim
        ;;
  *)
        echo "Usage: exim {start|stop|restart|reload|condrestart|status}"
        exit 1
esac

exit 0

