#!/bin/sh
#Dovecot prestart script, which needs to be placed in /usr/libexec/dovecot/prestartscript
/bin/systemctl -q is-enabled NetworkManager.service >/dev/null 2>&1 && /usr/bin/nm-online -q --timeout 30 ||: